CREATE TABLE `urlstore` (
  `shortId` int NOT NULL AUTO_INCREMENT,
  `longurl` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`shortId`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci